steps:
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - '${_DOCKERFILE}'
      - '-t'
      - '${_REGISTRY}/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA'
      - '.'

  - id: push
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGISTRY}/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA'

  - id: deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=${_REGISTRY}/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--concurrency=24'
      - '--timeout=300'

substitutions:
  _DOCKERFILE: 'Dockerfile'
  _SERVICE: 'pare'
  _REGISTRY: 'gcr.io'
  _REGION: 'us-central1'
